spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
greetings:
  message: "Bonjour je suis dev !"

---

spring:
  config:
    activate:
      on-profile: prod
greetings:
  message: "Bonjour je suis la prod !"